# Generated by Django 5.1.2 on 2025-12-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventcategory_alter_otp_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular User'), ('artist', 'Artist'), ('event_organizer', 'Event Organizer'), ('experience_provider', 'Experience Provider'), ('venue_owner', 'Venue Owner')], default='regular', max_length=30),
        ),
    ]
