# Generated by Django 5.1.2 on 2025-12-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='allowed_user_type',
            field=models.CharField(blank=True, choices=[('artist', 'Artist'), ('event_organizer', 'Event Organizer'), ('experience_provider', 'Experience Provider'), ('venue_owner', 'Venue Owner')], help_text='Which user type can post in this category', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='block_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
