# Generated by Django 6.0 on 2026-01-01 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventcategory_id_alter_otp_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_type', models.CharField(choices=[('regular', 'Regular User'), ('artist', 'Artist'), ('event_organizer', 'Event Organizer'), ('experience_provider', 'Experience Provider'), ('venue_owner', 'Venue Owner')], max_length=30)),
                ('note', models.TextField(blank=True, help_text='Why do you want to become a host?', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
