# Generated by Django 6.0 on 2026-01-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='maximum_capacity',
            field=models.PositiveIntegerField(default=0, help_text='0 for unlimited'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_type',
            field=models.CharField(choices=[('free', 'Free'), ('own_payment', 'Own Payment'), ('pluuto_payments', 'Pluuto Payments')], default='free', max_length=20),
        ),
    ]
