# Generated by Django 6.0 on 2026-01-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked'), ('finished', 'Finished')], default='pending', max_length=20),
        ),
    ]
