# Generated by Django 6.0 on 2026-02-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='host_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='host_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='host_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='host_profile_pics/'),
        ),
    ]
