# Generated by Django 6.0 on 2026-02-02 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_collaborationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScratchPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Prize image', null=True, upload_to='scratch_prizes/')),
                ('title', models.CharField(help_text='Prize title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Prize description', null=True)),
                ('code', models.CharField(blank=True, help_text='Prize code/coupon', max_length=100, null=True)),
                ('is_better_luck', models.BooleanField(default=False, help_text="Is this a 'Better luck next time' prize?")),
                ('total_count', models.IntegerField(default=-1, help_text='-1 for unlimited')),
                ('won_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scratch_prize_items', to='events.event')),
            ],
            options={
                'ordering': ['-is_better_luck', 'created_at'],
            },
        ),
    ]
