# Generated by Django 6.0 on 2026-02-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_notification_scratchprize'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
