# Generated by Django 6.0 on 2026-02-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_booking_paid_amount_booking_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured events appear on the home page'),
        ),
    ]
