# Generated by Django 6.0 on 2026-02-05 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_event_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_likes',
            field=models.ManyToManyField(blank=True, related_name='liked_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
