# Generated by Django 6.0 on 2026-02-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_hostcategory_user_host_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='scratchprize',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date for the prize', null=True),
        ),
    ]
