# Generated by Django 6.0 on 2026-02-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_event_booking_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='host_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
