# Generated by Django 6.0 on 2026-02-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_event_location_url_user_host_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
