# Generated by Django 6.0 on 2026-02-08 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_booking_booking_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_qr_code',
        ),
        migrations.AddField(
            model_name='event',
            name='can_edit_sensitive_data',
            field=models.BooleanField(default=False, help_text='Admin control: Allow host to edit date, time, location, price'),
        ),
        migrations.AddField(
            model_name='event',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendee_coins',
            field=models.PositiveIntegerField(default=0, help_text='Coins awarded for attending'),
        ),
        migrations.AlterField(
            model_name='event',
            name='qr_code_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='scratch_prizes',
            field=models.TextField(blank=True, help_text='Comma separated list of prizes', null=True),
        ),
        migrations.CreateModel(
            name='EventEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventUpdateNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_notifications', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_update_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
