# Generated by Django 6.0 on 2026-02-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_remove_event_event_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin_payment_note',
            field=models.TextField(blank=True, help_text='Note regarding admin payment to host', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='admin_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
