# Generated by Django 6.0 on 2026-02-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_event_admin_payment_note_event_admin_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_host',
            field=models.BooleanField(default=False),
        ),
    ]
