# Generated by Django 6.0 on 2026-02-14 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_user_is_verified_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
