# Generated by Django 6.0 on 2026-03-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('pending_payment', 'Pending Payment'), ('cancelled', 'Cancelled'), ('attended', 'Attended')], default='booked', max_length=20),
        ),
    ]
