# Generated by Django 6.0 on 2026-03-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_source',
            field=models.CharField(blank=True, help_text="How payment was verified (e.g., 'api' or 'webhook')", max_length=50, null=True),
        ),
    ]
