# Generated by Django 6.0 on 2026-03-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_user_country_code_appfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
